# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"!\n\x0e\x43hatbotRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0f\x43hatbotResponse\x12\r\n\x05reply\x18\x01 \x01(\t2R\n\x0b\x43hatService\x12\x43\n\nChatStream\x12\x17.chatbot.ChatbotRequest\x1a\x18.chatbot.ChatbotResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATBOTREQUEST']._serialized_start=26
  _globals['_CHATBOTREQUEST']._serialized_end=59
  _globals['_CHATBOTRESPONSE']._serialized_start=61
  _globals['_CHATBOTRESPONSE']._serialized_end=93
  _globals['_CHATSERVICE']._serialized_start=95
  _globals['_CHATSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
