module.exports = {
    CONTROLLER_PORT: 5000,
    CONTROLLER_GRPC_PORT: 6000,
    
    WORKER_BASE_PORT: 5001,
    WORKER_GRPC_BASE_PORT: 6001,
    
    NUM_WORKERS: 4,
    REPLICA_COUNT: 3,

    VNODES_PER_WORKER: 10, 

    HEARTBEAT_INTERVAL_MS: 3000,
    HEARTBEAT_TIMEOUT_MS: 8000,
    ENTRY_POINT_SCRIPT: 'src/kv_stores.js'
};